# This workflow will generate a PR for changes in dev into master for a skill

name: Pull to Cert
on: 
  push:
    branches: 
      - dev
  workflow_dispatch:

jobs:
  pull_changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: pull-request-action
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "cert"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_reviewer: 'neonreviewers'
          pr_assignee: 'neondaniel'